import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";
import { Providers } from "./providers"; // Adjust path if needed
import { SnackBarProvider } from "@/utils/snackbarContext";

export const metadata = {
  title: "Codeial Public School",
  description: "Generated by create next app",
  icons: { icon: "/schoolLogo.png" }, // Metadata-based favicon setup
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SnackBarProvider>
          <Providers>
            <div className="flex">
              {/* LEFT NAVBAR */}
              <aside className="w-[16%] md:w-[8%] lg:w-[16%]">
                <Navbar />
              </aside>
              
              {/* RIGHT CONTENT AREA */}
              <main className="w-[84%] md:w-[92%] lg:w-[84%] bg-[#F7F8FA] flex flex-col">
                <Header />
                {children}
                <Analytics />
              </main>
            </div>
          </Providers>
        </SnackBarProvider>
      </body>
  </html>
  );
}